### ISSUE TITLE
Doesn't handle flight changes

### ISSUE THREAD

**Issue by babehboi** [jdholtz/auto-southwest-check-in#101]
### Description

Unexpected error during fare check: IndexError('list index out of range')
Traceback (most recent call last):
  File "/home/user/auto-southwest-check-in/lib/flight_retriever.py", line 80, in _check_flight_fares
    fare_checker.check_flight_price(flight)
  File "/home/user/auto-southwest-check-in/lib/fare_checker.py", line 31, in check_flight_price
    flight_price = self._get_flight_price(flight)
  File "/home/user/auto-southwest-check-in/lib/fare_checker.py", line 44, in _get_flight_price
    flights, fare_type = self._get_matching_flights(flight)
  File "/home/user/auto-southwest-check-in/lib/fare_checker.py", line 75, in _get_matching_flights
    fare_type = fare_type_bounds[bound]["fareProductDetails"]["fareProductId"]
IndexError: list index out of range

### To Reproduce

1. Run with a configuration file.
2. Seemed to have been running fine for the past 2 days and it did not stop the script.
3. Exited script, and re-ran and worked just fine.
4. However, the flight that most likely threw the exception had a fare change.

### Expected Behavior

The fare change notification would trigger without an error.

### Version

4.1

**Comment by jdholtz** [comment]
If the flight was changed before this fare check, that would make sense why it would throw that error (the flight wasn't found). From what I can tell from the error and your explanation, you changed the return flight on your reservation and the new flight is now under a different reservation (confirmation number). Is this correct?

I haven't added functionality to deal with flight changes/cancellations. I will leave this issue open until I have added that logic.

> and it did not stop the script

Errors in fare checking won't stop the script. They will simply be ignored. I decided on this because fare checking isn't strictly necessary to the check-in, so it would be undesired for a fare check error to halt the check-in.

**Comment by babehboi** [comment]
Actually the confirmation number didn't change, only the flight date/time was changed.

As to the logic, I wonder if it's worth looking at the scheduled Date/UTC and verifying that it still is the same with the flight that's being checked? If not, end the old one and start up another instance of scheduling the flight check-in?

**Comment by babehboi** [comment]
Either that or throw out an error so one can rerun the script due to "Dummy you've changed your flight, we're no longer in synch" =) 

day before:
Successfully scheduled the following flights to check in for XXX XXX:
Flight from New York (LaGuardia) to San Jose at 2023-06-11 10:05:00 UTC

Successfully scheduled the following flights to check in for XXX XXX:
Flight from New York (LaGuardia) to San Jose at 2023-06-12 21:45:00 UTC

Just to get an idea - Confirmation number remained the same.

Although on a side note, since I haven't encountered it before, but say after 6/12 and that confirmation number is still in our config file, what, if any, error message will be thrown?

**Comment by jdholtz** [comment]
> Actually the confirmation number didn't change, only the flight date/time was changed.

That makes sense. I don't think this issue would actually occur if the confirmation number changed.

> If not, end the old one and start up another instance of scheduling the flight check-in?

That is exactly what I plan to do

 > Just to get an idea - Confirmation number remained the same.

Were you monitoring an account or a flight/reservation during this instance of the script?

>  say after 6/12 and that confirmation number is still in our config file, what, if any, error message will be thrown?

It would send you a message alerting you that the reservation has not been found (basically, it would act the same as if you were to input a random 6-digit alphanumeric). [Here](https://github.com/jdholtz/auto-southwest-check-in/blob/60f57201e0d11ace1095601a80d87013a7d1b871/lib/checkin_scheduler.py#L91) is the code that is triggered when this happens if you are interested.

**Comment by babehboi** [comment]
> Were you monitoring an account or a flight/reservation during this instance of the script?

I was actually doing both.
I had my account log in meanwhile I had 2 other flights for my cousin monitored.

The one specifically was a one way trip that had the issue that I was monitoring with her reservation number.

**Comment by jdholtz** [comment]
Did it automatically reschedule the check-in for the flight when it changed or did you have to restart the script?

**Comment by jdholtz** [comment]
This IndexError occurred because the script attempted to check fares for a flight that was canceled. Instead of directly fixing the error, I decided to handle flights being changed or canceled so fares won't be checked for unavailable flights in the first place. That leaves it open to find any other issues that could result in this error besides changing flights.
