### ISSUE TITLE
Support international check-ins

### ISSUE THREAD

**Issue by wootwoot1234** [jdholtz/auto-southwest-check-in#113]
### Description

I used [auto-southwest-check-in](https://github.com/jdholtz/auto-southwest-check-in) to check into to a flight to Mexico and it failed because it needs passport information, etc.  It would be great to support that as well.

**Comment by wootwoot1234** [comment]
Never mind, it looks like it still works to get you a good seat position (https://github.com/jdholtz/auto-southwest-check-in/issues/21) but you need to login and enter the additional data your self later.  I guess it would be good if it had a better error message but that's a nice to have.

**Comment by jdholtz** [comment]
Are you able to fill in your passport information before you check in? There is a note at the top of the README indicating to do this, but I'm not sure if that's possible. 

If it isn't, I can add on to that note to say that the check-in works but an error is still thrown. Unfortunately, it doesn't look like I can differentiate when a check-in fails due to needing passport information vs. just failing as they report the same error code.
