### ISSUE TITLE
For Mac Users with Default Python Install, Remind to Install SSL Certificates

### ISSUE THREAD

**Issue by greennayr** [jdholtz/auto-southwest-check-in#128]
### Description

When I tried to set this up, I ran into an issue where I basically got a bunch of errors and finally a crash that showed: [SSL: CERTIFICATE_VERIFY_FAILED] 

I root caused to my mac being setup with a python install that did not include an certificates by default. The solution is in this stack overflow question: https://stackoverflow.com/questions/42098126/mac-osx-python-ssl-sslerror-ssl-certificate-verify-failed-certificate-verify

**Comment by jdholtz** [comment]
Thanks for the request! I decided to make a separate FAQ section to the Readme and added the answer to this question in it, since it has come up fairly often. You can find the answer to the question [here](https://github.com/jdholtz/auto-southwest-check-in/tree/develop#while-attempting-to-run-this-script-i-get-a-ssl-certificate_verify_failed-error-how-can-i-fix-it).
