### ISSUE TITLE
Google Chrome out of date

### ISSUE THREAD

**Issue by grantland** [jdholtz/auto-southwest-check-in#23]
I'm now getting an error that my Google Chrome is out of date. I think somehow the selenium dependency got updated to require 108 while my containers are stuck at 107. 

Is there a way to ensure that one doesn't get updated and the other doesn't?

Also, is there a way to update the existing containers?

Lastly, is there a way to get notified of failures like this?

Thanks!

```Traceback (most recent call last):
  File "/app/southwest.py", line 35, in <module>
    set_up(arguments)
  File "/app/southwest.py", line 26, in set_up
    account.get_checkin_info(confirmation_number)
  File "/app/lib/account.py", line 44, in get_checkin_info
    self.refresh_headers()
  File "/app/lib/account.py", line 51, in refresh_headers
    self.headers = webdriver.get_info()
  File "/app/lib/webdriver.py", line 30, in get_info
    driver = Chrome(options=options, seleniumwire_options=seleniumwire_options)
  File "/usr/local/lib/python3.10/dist-packages/seleniumwire/undetected_chromedriver/webdriver.py", line 61, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/undetected_chromedriver/__init__.py", line 401, in __init__
    super(Chrome, self).__init__(
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/chrome/webdriver.py", line 70, in __init__
    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/chromium/webdriver.py", line 92, in __init__
    RemoteWebDriver.__init__(
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 275, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.10/dist-packages/undetected_chromedriver/__init__.py", line 589, in start_session
    super(selenium.webdriver.chrome.webdriver.WebDriver, self).start_session(
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 365, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 430, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:55479
from session not created: This version of ChromeDriver only supports Chrome version 108
Current browser version is 107.0.5304.110
Stacktrace:
#0 0x55a44e92a2a3 <unknown>
#1 0x55a44e6e8f77 <unknown>
#2 0x55a44e715fd7 <unknown>
#3 0x55a44e70cf89 <unknown>
#4 0x55a44e74e0b7 <unknown>
#5 0x55a44e74da5f <unknown>
#6 0x55a44e745903 <unknown>
#7 0x55a44e718ece <unknown>
#8 0x55a44e719fde <unknown>
#9 0x55a44e97a63e <unknown>
#10 0x55a44e97db79 <unknown>
#11 0x55a44e96089e <unknown>
#12 0x55a44e97ea83 <unknown>
#13 0x55a44e953505 <unknown>
#14 0x55a44e99fca8 <unknown>
#15 0x55a44e99fe36 <unknown>
#16 0x55a44e9bb333 <unknown>
#17 0x7f7e923eb402 <unknown>

```

**Comment by jdholtz** [comment]
Hi! This is an annoying issue I run into frequently as well. It isn’t a problem with selenium, but undetected_chromedriver. It always downloads the latest version (because I didn’t specify a version). There is a [PR](https://github.com/ultrafunkamsterdam/undetected-chromedriver/pull/823) to fix this issue, so I hope that gets merged soon. 

However, to work around this for now you can rebuild the container (and update chrome to the latest version in the process) by running the `docker build` command with the `--no-cache` flag. 

I am currently doing a refactor of this script, so I will also add a way to catch unexpected errors like this and send a notification. 

Did this error occur when you started the container or after it has been running for a while?

An unrelated question: Is the script correctly getting your reservation info? Over the last few days, the Southwest website has been returning a “Reservation not found” for my reservations instead of “too early to check in” (which causes the script to fail entirely when using a confirmation number instead of login credentials).

**Comment by grantland** [comment]
Thanks! Just tested `docker build` with `--no-cache` seems to work for now! Do you know if there's a way to manually re-run each instance with the new image? Right now it seems like I have to manually kill and recreate each instance.

> I am currently doing a refactor of this script, so I will also add a way to catch unexpected errors like this and send a notification.

That would be amazing! Also exiting on error would be great too.

> Did this error occur when you started the container or after it has been running for a while?

I'm not entirely sure, but it does seem to occur if an instance is restarted with `docker restart` which I assume would also be a problem for me since I have a cronjob to restart my machine once every week.

> An unrelated question: Is the script correctly getting your reservation info? Over the last few days, the Southwest website has been returning a “Reservation not found” for my reservations instead of “too early to check in” (which causes the script to fail entirely when using a confirmation number instead of login credentials).

I tested and came up with #24 so it seems to work. It just won't stop trying though.

**Comment by jdholtz** [comment]
> Do you know if there's a way to manually re-run each instance with the new image? Right now it seems like I have to manually kill and recreate each instance.

Due to the way containers are made to be immutable, each instance has to be stopped, removed, and restarted. The best way to do this would probably be to write a bash script or look up a chain of docker commands you can use. 

Alternatively, if all flights are under the same account, you can provide your username and password to the script and it will set up check ins for all flights under that account, removing the need for more than one container running at a time.

**Comment by grantland** [comment]
Ah that makes sense!

> Alternatively, if all flights are under the same account, you can provide your username and password to the script and it will set up check ins for all flights under that account, removing the need for more than one container running at a time.

Interesting, would my cron restart also restart the entire script and therefore would catch any new reservations and technically clean up any cancelled reservations?

**Comment by jdholtz** [comment]
> Interesting, would my cron restart also restart the entire script and therefore would catch any new reservations and technically clean up any cancelled reservations?

Yes. However, I should be finalizing my reactor soon which takes care of all of this within the script itself (it checks for new flights every X hours and removes old flights).

I will close this issue for now. Hopefully that PR I mentioned above will be merged soon (as it will create a problem if the script runs for long periods of time). If not, I’ll have to hard code the version of Chrome somehow.
