### ISSUE TITLE
Hang during setting headers_set

### ISSUE THREAD

**Issue by spacezorro** [jdholtz/auto-southwest-check-in#234]
### Version

7.2

### Browser Version

Chromium 112.0.5615.49

### Description

Sometimes it just gets hung up at "Waiting for headers_set to be set"

This is not consistent and restarting the whole thing a couple times will solve the problem.

### To Reproduce

I am running this with an account. I have tried it with a single reservation and it is the same.

### Expected Behavior

a timeout where the page is reloaded or an error thrown after an amount of time

### Relevant logs and program output

```sh
2024-03-01 17:23:10 DEBUG Process-1[reservation_monitor:62]: Lock acquired
2024-03-01 17:23:12 DEBUG Process-1[checkin_scheduler:50]: Refreshing headers for current session
2024-03-01 17:23:13 DEBUG Process-1[webdriver:103]: Starting webdriver for current session
2024-03-01 17:25:21 DEBUG Process-1[webdriver:119]: Using browser version: 112.0.5615.49
2024-03-01 17:25:21 DEBUG Process-1[webdriver:123]: Loading Southwest Check-In page
2024-03-01 17:28:50 DEBUG Process-1[webdriver:65]: Waiting for valid headers
2024-03-01 17:28:50 DEBUG Process-1[webdriver:152]: Waiting for headers_set to be set
```

### Additional context

It looks like it is getting caught in the while loop in the webdriver.py _wait_for_attribute function

**Comment by jdholtz** [comment]
Yeah, it may be a good idea to add a timeout for this, although for slow networks web responses can take a minute to come through. 

Are you running the script in Docker? If not, are you able to upgrade your Chromium version. An older browser version could be the issue as to why a response is not being received.

Also, could you send the relevant logs for when you run into the issue with an account instead of a reservation? Since account mode actually needs the webpage to fully load in order to log in, it’s more helpful in determining what exactly is failing.

**Comment by spacezorro** [comment]
Not in docker. I'm running in a venv. I will upgrade Chromium, run w/ acct, and resend logs.

**Comment by spacezorro** [comment]
Is it possible we are getting a valid page load but it is one of those "Are you a robot" or "This traffic looks suspicious" pages?

Is there something I can do to get more logging? I have it set to 1

**Comment by jdholtz** [comment]
> Is it possible we are getting a valid page load but it is one of those "Are you a robot" or "This traffic looks suspicious" pages?

Probably not because I've never seen that on Southwest's website.

> Is there something I can do to get more logging? I have it set to 1

Not for logging (the notification level doesn't have to do with the level of logging within the script. That's only controlled with the `--verbose` flag). However, you can change `headless=True` to `headed=True` on line 118 of `lib/webdriver.py` to see the browser loading the webpage which would definitely help us debug the issue.

**Comment by spacezorro** [comment]
OK I have this on a headless machine and I just updated to 7.3

I will move it to a local machine and try with "headed"

**Comment by spacezorro** [comment]
This was my bad.

I updated the repo and didn't reinstall pip requirements

I moved the config out of the way and ran "python3 southwest.py -v Conf# First Last"

I found this in the output
```
AttributeError: 'WebDriver' object has no attribute 'add_cdp_listener'
```

I searched, found #233, did a "pip install -r requirements.txt", and it works now.

**Comment by jdholtz** [comment]
Great to hear that it’s working now. Whenever there is a new version, I add the necessary steps the user needs to perform after upgrading in the `Upgrading` section of the version’s Changelog which usually includes upgrading the requirements.
