### ISSUE TITLE
Add jitter to requests time(s)

### ISSUE THREAD

**Issue by nicseltzer** [jdholtz/auto-southwest-check-in#245]
Add a jitter / variance to request times within a range of, say, 30 minutes. Test to see if this reduces the number of 403 errors encountered.

**Comment by jdholtz** [comment]
Hi. Could you please add suggestions about the 403 to #230 or use GitHub Discussions (it also doesn't follow the template) in the future?

> Add a jitter / variance to request times within a range of, say, 30 minutes. Test to see if this reduces the number of 403 errors encountered.

This won't work because many people (myself included) get the 403 on the very first request they have. They aren't seeing it after some subsequent requests have been made. Therefore, adding a variance to the request times unfortunately won't have an effect. Also, the underlying issue is that the headers Southwest returns from the browser are invalid which causes the 403, not when the requests are done (as far as I know). Myself and others have done testing with request variance and it hasn't returned positive results.
