### ISSUE TITLE
Fare Check

### ISSUE THREAD

**Issue by ctkubik** [jdholtz/auto-southwest-check-in#38]
I am not sure if this is possible, but it would be pretty cool if you could add the fare you paid and have the system check if the fare went down for the same flight.

Since the system knows the flights and confirmation code...maybe use a script like

Southwest.py CONFIRMATION $/POINTS XXXXX

So, you'd be telling the system to attribute either dollars or points to the flights/confirmation.  If the flight drops in cost a notification is sent.

**Comment by jdholtz** [comment]
This should be possible. There are other scripts that have done this in the past and I have thought about adding this as well. 

However, I think this is out of the scope of the project. What would be better, in my opinion, is to have a separate project that handles this. Then, these this script could call the other script to run once a day (sorta like a plug-in system). 

I’ll look into how complicated this would be. I’m thinking it’ll be a huge addition.

**Comment by schmeed** [comment]
Upvoting the separate project idea.

**Comment by jdholtz** [comment]
I was able to spend some time on this today and successfully reverse engineered the Southwest API to extract this information. Since it is much easier than I originally thought and it will need functionality already included in this script, I will add it to this project instead of creating a new one. 

@ctkubik I wanted to verify this process with you before proceeding forward to ensure I include what you expect: 

The script will look for the flight (only the one with the same exact departure time, day, departure airport, and arrival airport) on the same page you look at when hitting the “Change” button on the website. If it sees  negative points/$, it will send a notification to the user letting them know of this price drop. 

Let me know if anything is incorrect or not what you expect.

**Comment by babehboi** [comment]
I would like to totally say yes to that logic. Otherwise I would think it would be more difficult with too many other variables involved (aka nonstop vs stops etc)

**Comment by ctkubik** [comment]
> I was able to spend some time on this today and successfully reverse engineered the Southwest API to extract this information. Since it is much easier than I originally thought and it will need functionality already included in this script, I will add it to this project instead of creating a new one.
> 
> @ctkubik I wanted to verify this process with you before proceeding forward to ensure I include what you expect:
> 
> The script will look for the flight (only the one with the same exact departure time, day, departure airport, and arrival airport) on the same page you look at when hitting the “Change” button on the website. If it sees negative points/$, it will send a notification to the user letting them know of this price drop.
> 
> Let me know if anything is incorrect or not what you expect.

You nailed it...the same exact flight as it is booked.

**Comment by jdholtz** [comment]
Hey everyone. I just finished implementing this feature on the [fare_checker](https://github.com/jdholtz/auto-southwest-check-in/tree/fare_checker) branch. If you would like to test it out, you can run `git pull && git checkout fare_checker`. It is disabled by default, but there is documentation in the Configuration doc on how to enable it.

Check out #73 for more details. If you try it out, let me know how it works. Additionally, if you have any feedback to improve or change something, you can comment here or in the PR.

**Comment by babehboi** [comment]
@jdholtz - So far so good. It seems to be working. I do have several questions:

> 2023-04-17 10:31:31 DEBUG Process-1[flight_retriever]: Checking fares for 2 flights
> 2023-04-17 10:31:31 DEBUG Process-1[fare_checker]: Checking current price for flight
> 2023-04-17 10:31:31 DEBUG Process-1[fare_checker]: Fetching reservation information
> 2023-04-17 10:31:31 DEBUG Process-1:2[checkin_handler]: Sleeping until ten minutes before check-in...
> 2023-04-17 10:31:36 DEBUG Process-1[utils]: Successfully made request after 1 attempts
> 2023-04-17 10:31:36 DEBUG Process-1[fare_checker]: Retrieving search information for the current flight
> 2023-04-17 10:31:42 DEBUG Process-1[utils]: Successfully made request after 1 attempts
> 2023-04-17 10:31:42 DEBUG Process-1[fare_checker]: Retrieving matching flights
> 2023-04-17 10:31:44 DEBUG Process-1[utils]: Successfully made request after 1 attempts
> 2023-04-17 10:31:44 DEBUG Process-1[fare_checker]: Found 13 matching flights
> 2023-04-17 10:31:44 DEBUG Process-1[fare_checker]: Flight price change found for 0 USD

> 2023-04-17 10:31:44 DEBUG Process-1[fare_checker]: Checking current price for flight
> 2023-04-17 10:31:44 DEBUG Process-1[fare_checker]: Fetching reservation information
> 2023-04-17 10:31:50 DEBUG Process-1[utils]: Successfully made request after 1 attempts
> 2023-04-17 10:31:50 DEBUG Process-1[fare_checker]: Retrieving search information for the current flight
> 2023-04-17 10:31:55 DEBUG Process-1[utils]: Successfully made request after 1 attempts
> 2023-04-17 10:31:55 DEBUG Process-1[fare_checker]: Retrieving matching flights
> 2023-04-17 10:31:57 DEBUG Process-1[utils]: Successfully made request after 1 attempts
> 2023-04-17 10:31:57 DEBUG Process-1[fare_checker]: Found 12 matching flights
> 2023-04-17 10:31:57 DEBUG Process-1[fare_checker]: Flight price change found for 0 USD
> 2023-04-17 10:31:57 DEBUG Process-1[flight_retriever]: Sleeping for 86350 seconds

1. Since it looks like it's pulling all flights for the day, is it checking all the prices for that date to determine if there are any specific changes to all the flights for that date or is it solely looking at the flight that we have booked?
2. If it's the latter, where it's checking the flight we have booked, I wonder if in verbose we'd pull the flight number in to be a little more specific like Flight 1111 price change found for 0 USD.
3. If it's the former, will it indicate which flights and the different fares we'd expect from it? Or will it list the fare with the largest decrease?
4. If it is also checking all flights, I wonder if it would be worth also adding a flag so that we can filter the flights being checked to only the non-stop flights to be checked?

Thanks for all the work you've put into this!

**Comment by jdholtz** [comment]
Thanks for testing @babehboi. 

1. It only looks for the flight that has been booked (AKA the one with the same exact departure time)

2. Yes, that is definitely possible. However, my goal with the log information is to not log any information that could identify the user in any way (I want users to be able to upload their logs without having to worry about leaking sensitive information). If you want to, you can identify the order of how the flights are checked because they are in the same order that the script schedules check-ins for them (albeit, this is annoying if you want to do this). Let me know if you have any potential solutions to this.

3. Let me know if you want to potentially have a feature like this. As explained in 1, it currently only checks the same flight.
