### ISSUE TITLE
Time Seems off in logs

### ISSUE THREAD

**Issue by edshaw42** [jdholtz/auto-southwest-check-in#46]
### Description

<img width="468" alt="image" src="https://user-images.githubusercontent.com/85707702/219230852-ed6827ee-5e3e-4c71-bc7b-36f846635006.png">

I believe the times it says in the logs are incorrect because the UTC time and date are wrong for my flights. 

### To Reproduce

run script passing confirmation first last

### Expected Behavior

Date/time to be correct

**Comment by jdholtz** [comment]
If I’m getting this correct, your first flight time should be 8:15pm CT (Nashville TZ) on 2023-02-16 and your returning flight should be at 1:55pm (Orlando TZ) on 2023-02-20. Are both incorrect?

**Comment by jdholtz** [comment]
Hey @edshaw42, did you ever verify if the times were accurate or not?

**Comment by babehboi** [comment]
I'm pretty sure it's probably right. Thank you for the script by the way. I tried it yesterday and works wonderfully! 

That being said I was about to comment that the days were wrong until I noticed it said UTC. And did my own conversions to check up against it.

But I could be wrong :: shrugs ::

It seems like your script is pulling the appropriate time to which to check in via their system it wouldn't matter about timezones since you're using the UTC of the system that has polled the data?

Otherwise can't wait to see when you're able to do the price check. I've been trying this other script but haven't been successful in deploying just yet.

**Comment by jdholtz** [comment]
> Thank you for the script by the way. I tried it yesterday and works wonderfully!

Glad people are finding it useful!

> It seems like your script is pulling the appropriate time to which to check in via their system it wouldn't matter about timezones since you're using the UTC of the system that has polled the data?

UTC is the easiest to use to ensure the time will always correct. Southwest gives the airport code and time of the flight. In this [file](https://github.com/jdholtz/auto-southwest-check-in/blob/master/utils/airport_timezones.json), the matching TZ is retrieved from the code. Then, the time is converted from that TZ to UTC. 

> Otherwise can't wait to see when you're able to do the price check

I’ll definitely try to include that at some point, although it’ll take some time. I’m still not sure on whether to include it as a separate project that is integrated with this script or keep it in this project. Any comments and/or feedback on #38 would be appreciated!

**Comment by schmeed** [comment]
> I’ll definitely try to include that at some point, although it’ll take some time. I’m still not sure on whether to include it as a separate project that is integrated with this script or keep it in this project. Any comments and/or feedback on #38 would be appreciated!

If I have vote, I would vote for a separate project.  I think it could overly complicate the check-in script.  It needs to remain lightweight and single purposed, IMO.
